-- About 50 editable sample games. Re-running the seed updates metadata by title.
insert into public.games (title, cover_url, release_year, genre, tags, description) values
('A Way Out', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1222700/header.jpg', 2018, 'Aventure', array['coop','terminé'], 'Une évasion pensée exclusivement pour deux joueurs.'),
('Among Us', 'https://cdn.cloudflare.steamstatic.com/steam/apps/945360/header.jpg', 2018, 'Party game', array['coop','déduction'], 'Déduction sociale et trahisons entre équipiers.'),
('Baldur''s Gate 3', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg', 2023, 'RPG', array['coop','tour par tour'], 'Une grande aventure de rôle aux choix multiples.'),
('Borderlands 2', 'https://cdn.cloudflare.steamstatic.com/steam/apps/49520/header.jpg', 2012, 'FPS', array['coop','action'], 'Chasse au loot déjantée sur Pandora.'),
('Castle Crashers', 'https://cdn.cloudflare.steamstatic.com/steam/apps/204360/header.jpg', 2012, 'Beat’em up', array['coop','action'], 'Un beat’em up coloré et chaotique.'),
('Chained Together', 'https://cdn.cloudflare.steamstatic.com/steam/apps/2567870/header.jpg', 2024, 'Plateforme', array['coop','difficile'], 'Grimpez hors de l’enfer, littéralement enchaînés.'),
('Content Warning', 'https://cdn.cloudflare.steamstatic.com/steam/apps/2881650/header.jpg', 2024, 'Horreur', array['coop','horreur'], 'Filmez des créatures pour devenir viral.'),
('Core Keeper', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1621690/header.jpg', 2024, 'Survie', array['coop','early access'], 'Explorez un monde souterrain et bâtissez votre base.'),
('Cuphead', 'https://cdn.cloudflare.steamstatic.com/steam/apps/268910/header.jpg', 2017, 'Run and gun', array['coop','difficile'], 'Des boss exigeants dans un dessin animé des années 1930.'),
('Deep Rock Galactic', 'https://cdn.cloudflare.steamstatic.com/steam/apps/548430/header.jpg', 2020, 'FPS', array['coop','action'], 'Nains de l’espace, grottes procédurales et insectes.'),
('Don''t Starve Together', 'https://cdn.cloudflare.steamstatic.com/steam/apps/322330/header.jpg', 2016, 'Survie', array['coop','survie'], 'Survivez ensemble dans un monde hostile et étrange.'),
('Dying Light', 'https://cdn.cloudflare.steamstatic.com/steam/apps/239140/header.jpg', 2015, 'Action', array['coop','horreur'], 'Parkour et zombies dans une ville ouverte.'),
('Escape Simulator', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1435790/header.jpg', 2021, 'Puzzle', array['coop','énigmes'], 'Des escape rooms interactives conçues pour coopérer.'),
('Factorio', 'https://cdn.cloudflare.steamstatic.com/steam/apps/427520/header.jpg', 2020, 'Gestion', array['coop','automatisation'], 'Construisez et optimisez une usine tentaculaire.'),
('Fall Guys', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/header.jpg', 2020, 'Party game', array['multijoueur','action'], 'Courses d’obstacles absurdes et colorées.'),
('For The King', 'https://cdn.cloudflare.steamstatic.com/steam/apps/527230/header.jpg', 2018, 'RPG', array['coop','tour par tour'], 'Un RPG tactique inspiré des jeux de plateau.'),
('Gang Beasts', 'https://cdn.cloudflare.steamstatic.com/steam/apps/285900/header.jpg', 2017, 'Party game', array['multijoueur','fun'], 'Bagarres molles et arènes dangereuses.'),
('Grounded', 'https://cdn.cloudflare.steamstatic.com/steam/apps/962130/header.jpg', 2022, 'Survie', array['coop','survie'], 'Survivez dans un jardin après avoir été miniaturisés.'),
('Human Fall Flat', 'https://cdn.cloudflare.steamstatic.com/steam/apps/477160/header.jpg', 2016, 'Puzzle', array['coop','physique'], 'Énigmes physiques avec des personnages très souples.'),
('It Takes Two', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1426210/header.jpg', 2021, 'Aventure', array['coop','terminé'], 'Une aventure inventive entièrement construite pour deux.'),
('Keep Talking and Nobody Explodes', 'https://cdn.cloudflare.steamstatic.com/steam/apps/341800/header.jpg', 2015, 'Puzzle', array['coop','communication'], 'Désamorcez une bombe grâce aux instructions de votre partenaire.'),
('Left 4 Dead 2', 'https://cdn.cloudflare.steamstatic.com/steam/apps/550/header.jpg', 2009, 'FPS', array['coop','horreur'], 'Une référence de la coopération contre des hordes infectées.'),
('Lethal Company', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1966720/header.jpg', 2023, 'Horreur', array['coop','horreur','early access'], 'Récupérez de la ferraille sur des lunes mortelles.'),
('Lovers in a Dangerous Spacetime', 'https://cdn.cloudflare.steamstatic.com/steam/apps/252110/header.jpg', 2015, 'Action', array['coop','espace'], 'Pilotez ensemble un vaisseau rempli de postes à gérer.'),
('Minecraft', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1672970/header.jpg', 2011, 'Sandbox', array['coop','créatif'], 'Explorez, construisez et survivez dans un monde de blocs.'),
('Moving Out', 'https://cdn.cloudflare.steamstatic.com/steam/apps/996770/header.jpg', 2020, 'Party game', array['coop','fun'], 'Un simulateur de déménagement basé sur le chaos.'),
('No Man''s Sky', 'https://cdn.cloudflare.steamstatic.com/steam/apps/275850/header.jpg', 2016, 'Exploration', array['coop','espace'], 'Explorez une galaxie procédurale sans limites.'),
('Operation: Tango', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1335790/header.jpg', 2021, 'Puzzle', array['coop','communication'], 'Un agent et un hacker doivent constamment communiquer.'),
('Overcooked! 2', 'https://cdn.cloudflare.steamstatic.com/steam/apps/728880/header.jpg', 2018, 'Party game', array['coop','cuisine'], 'Cuisinez ensemble dans des cuisines impossibles.'),
('Palworld', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1623730/header.jpg', 2024, 'Survie', array['coop','early access'], 'Capture, survie et construction dans un monde ouvert.'),
('PAYDAY 2', 'https://cdn.cloudflare.steamstatic.com/steam/apps/218620/header.jpg', 2013, 'FPS', array['coop','action'], 'Organisez des braquages en équipe.'),
('Phasmophobia', 'https://cdn.cloudflare.steamstatic.com/steam/apps/739630/header.jpg', 2020, 'Horreur', array['coop','horreur','early access'], 'Identifiez des fantômes avec votre matériel d’enquête.'),
('Portal 2', 'https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg', 2011, 'Puzzle', array['coop','terminé','énigmes'], 'Une campagne coopérative brillante autour des portails.'),
('Pummel Party', 'https://cdn.cloudflare.steamstatic.com/steam/apps/880940/header.jpg', 2018, 'Party game', array['multijoueur','fun'], 'Un jeu de plateau cruel rempli de mini-jeux.'),
('Raft', 'https://cdn.cloudflare.steamstatic.com/steam/apps/648800/header.jpg', 2022, 'Survie', array['coop','survie'], 'Développez votre radeau au milieu d’un océan hostile.'),
('Risk of Rain 2', 'https://cdn.cloudflare.steamstatic.com/steam/apps/632360/header.jpg', 2020, 'Roguelite', array['coop','action'], 'Un roguelite 3D frénétique aux combinaisons infinies.'),
('Rocket League', 'https://cdn.cloudflare.steamstatic.com/steam/apps/252950/header.jpg', 2015, 'Sport', array['multijoueur','compétitif'], 'Du football avec des voitures propulsées.'),
('Satisfactory', 'https://cdn.cloudflare.steamstatic.com/steam/apps/526870/header.jpg', 2024, 'Gestion', array['coop','automatisation'], 'Construisez une méga-usine à la première personne.'),
('Sea of Thieves', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1172620/header.jpg', 2020, 'Aventure', array['coop','pirates'], 'Naviguez et pillez dans un monde de pirates partagé.'),
('Spelunky 2', 'https://cdn.cloudflare.steamstatic.com/steam/apps/418530/header.jpg', 2020, 'Roguelite', array['coop','difficile'], 'Explorez des cavernes générées et souvent impitoyables.'),
('Stardew Valley', 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg', 2016, 'Simulation', array['coop','détente'], 'Cultivez une ferme et participez à la vie du village.'),
('Terraria', 'https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg', 2011, 'Sandbox', array['coop','aventure'], 'Creusez, construisez et combattez dans un vaste monde 2D.'),
('The Escapists 2', 'https://cdn.cloudflare.steamstatic.com/steam/apps/641990/header.jpg', 2017, 'Stratégie', array['coop','évasion'], 'Préparez minutieusement votre évasion de prison.'),
('The Forest', 'https://cdn.cloudflare.steamstatic.com/steam/apps/242760/header.jpg', 2018, 'Survie', array['coop','horreur'], 'Survivez à un crash dans une forêt peuplée de cannibales.'),
('Trine 4', 'https://cdn.cloudflare.steamstatic.com/steam/apps/690640/header.jpg', 2019, 'Plateforme', array['coop','énigmes'], 'Trois héros combinent leurs talents dans des décors féeriques.'),
('Unrailed!', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1016920/header.jpg', 2020, 'Party game', array['coop','gestion'], 'Construisez la voie ferrée devant un train qui ne s’arrête pas.'),
('Valheim', 'https://cdn.cloudflare.steamstatic.com/steam/apps/892970/header.jpg', 2021, 'Survie', array['coop','early access'], 'Survivez et explorez un purgatoire viking.'),
('Vampire Survivors', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1794680/header.jpg', 2022, 'Roguelite', array['coop','action'], 'Survivez à des vagues massives avec des builds démesurés.'),
('We Were Here', 'https://cdn.cloudflare.steamstatic.com/steam/apps/582500/header.jpg', 2017, 'Puzzle', array['coop','communication'], 'Deux explorateurs séparés communiquent par radio.'),
('We Were Here Forever', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1341290/header.jpg', 2022, 'Puzzle', array['coop','communication'], 'Une longue aventure d’énigmes asymétriques à deux.'),
('PlateUp!', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1599600/header.jpg', 2022, 'Gestion', array['coop','cuisine'], 'Construisez et automatisez le restaurant de vos rêves.')
on conflict (title) do update set
  cover_url = excluded.cover_url,
  release_year = excluded.release_year,
  genre = excluded.genre,
  tags = excluded.tags,
  description = excluded.description;
